Resources:
  # ==============================================================================
  # CIS AWS Foundations Benchmark v1.4.0 - Conformance Pack
  # ==============================================================================
  
  # 1.4 - Ensure no root account access key exists
  RootAccountAccessKeyCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-1-4-root-account-access-key
      Source:
        Owner: AWS
        SourceIdentifier: IAM_ROOT_ACCESS_KEY_CHECK

  # 1.5 - Ensure MFA is enabled for the root account
  RootAccountMFACheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-1-5-root-account-mfa
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_MFA_ENABLED

  # 1.6 - Ensure hardware MFA is enabled for the root account
  RootAccountHardwareMFACheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-1-6-root-account-hardware-mfa
      Source:
        Owner: AWS
        SourceIdentifier: ROOT_ACCOUNT_HARDWARE_MFA_ENABLED

  # 1.10 - Ensure multi-factor authentication (MFA) is enabled for all IAM users
  IAMUserMFACheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-1-10-iam-user-mfa
      Source:
        Owner: AWS
        SourceIdentifier: IAM_USER_MFA_ENABLED

  # 1.14 - Ensure access keys are rotated every 90 days or less
  AccessKeysRotatedCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-1-14-access-keys-rotated
      Source:
        Owner: AWS
        SourceIdentifier: ACCESS_KEYS_ROTATED
      InputParameters:
        maxAccessKeyAge: 90

  # 1.16 - Ensure IAM policies that allow full "*:*" administrative privileges are not attached
  IAMPolicyNoStatementsWithAdminAccessCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-1-16-iam-no-admin-policy
      Source:
        Owner: AWS
        SourceIdentifier: IAM_POLICY_NO_STATEMENTS_WITH_ADMIN_ACCESS

  # 2.1.1 - Ensure S3 Bucket Policy is set to deny HTTP requests
  S3BucketSSLRequestsOnlyCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-1-1-s3-bucket-ssl-requests-only
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SSL_REQUESTS_ONLY

  # 2.1.2 - Ensure MFA Delete is enabled on S3 buckets
  S3BucketVersioningEnabledCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-1-2-s3-bucket-versioning-enabled
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED

  # 2.1.3 - Ensure S3 buckets are encrypted at rest
  S3BucketServerSideEncryptionEnabledCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-1-3-s3-bucket-encryption
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED

  # 2.1.4 - Ensure S3 buckets have public access blocks enabled
  S3BucketPublicReadProhibitedCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-1-4-s3-no-public-read
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED

  S3BucketPublicWriteProhibitedCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-1-4-s3-no-public-write
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED

  # 2.2.1 - Ensure EBS volumes are encrypted
  EncryptedVolumesCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-2-1-ebs-encryption
      Source:
        Owner: AWS
        SourceIdentifier: ENCRYPTED_VOLUMES

  # 2.3.1 - Ensure RDS instances are encrypted
  RDSStorageEncryptedCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-2-3-1-rds-encryption
      Source:
        Owner: AWS
        SourceIdentifier: RDS_STORAGE_ENCRYPTED

  # 3.1 - Ensure CloudTrail is enabled in all regions
  CloudTrailEnabledCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-3-1-cloudtrail-enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_ENABLED

  # 3.2 - Ensure CloudTrail log file validation is enabled
  CloudTrailLogFileValidationEnabledCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-3-2-cloudtrail-log-file-validation
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_LOG_FILE_VALIDATION_ENABLED

  # 3.3 - Ensure the S3 bucket used to store CloudTrail logs is not publicly accessible
  CloudTrailS3BucketPublicAccessCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-3-3-cloudtrail-s3-no-public-access
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED

  # 3.4 - Ensure CloudTrail trails are integrated with CloudWatch Logs
  CloudTrailCloudWatchLogsEnabledCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-3-4-cloudtrail-cloudwatch-logs
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_CLOUD_WATCH_LOGS_ENABLED

  # 3.7 - Ensure CloudTrail logs are encrypted at rest using KMS CMKs
  CloudTrailEncryptionEnabledCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-3-7-cloudtrail-encryption
      Source:
        Owner: AWS
        SourceIdentifier: CLOUD_TRAIL_ENCRYPTION_ENABLED

  # 4.1 - Ensure no security groups allow ingress from 0.0.0.0/0 to port 22
  RestrictedSSHCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-4-1-restricted-ssh
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED

  # 4.2 - Ensure no security groups allow ingress from 0.0.0.0/0 to port 3389
  RestrictedRDPCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-4-2-restricted-rdp
      Source:
        Owner: AWS
        SourceIdentifier: RESTRICTED_INCOMING_TRAFFIC
      InputParameters:
        blockedPort1: 3389

  # 4.3 - Ensure the default security group of every VPC restricts all traffic
  VPCDefaultSecurityGroupClosedCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-4-3-vpc-default-sg-closed
      Source:
        Owner: AWS
        SourceIdentifier: VPC_DEFAULT_SECURITY_GROUP_CLOSED

  # 5.1 - Ensure CloudWatch log group retention is set
  CloudWatchLogGroupRetentionCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-5-1-cloudwatch-log-retention
      Source:
        Owner: AWS
        SourceIdentifier: CW_LOGGROUP_RETENTION_PERIOD_CHECK
      InputParameters:
        MinRetentionTime: 90

  # 5.3 - Ensure CloudWatch alarms exist for unauthorized API calls
  CloudWatchAlarmActionCheck:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: cis-5-3-cloudwatch-alarm-action
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDWATCH_ALARM_ACTION_CHECK
